<?php
$errors=[];$done=false;
function h($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
function p($k,$d=''){return trim((string)($_POST[$k]??$d));}
function btcaddr($v){return (bool)preg_match('/^(bc1|tb1|bcrt1|[13mn2])[a-zA-HJ-NP-Z0-9]{25,90}$/',$v);} 
function w($path,$content){$dir=dirname($path);if(!is_dir($dir))mkdir($dir,0755,true);file_put_contents($path,$content,LOCK_EX);} 
function keygen($n=32){return bin2hex(random_bytes($n));}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $base=rtrim(p('base_url'),'/');$fee=p('fee_address');$dark=p('dark_address');$rate=(float)p('btc_usd_rate');$ap=p('admin_password');$ap2=p('admin_password2');
  if(!filter_var($base,FILTER_VALIDATE_URL))$errors[]='Enter a valid base URL.';
  if(!btcaddr($fee))$errors[]='Enter a valid fee Bitcoin address.';
  if(!btcaddr($dark))$errors[]='Enter a valid Dark-Money Bitcoin address.';
  if($rate<=0)$errors[]='Enter a valid BTC/USD rate.';
  if(strlen($ap)<12)$errors[]='Admin password must contain at least 12 characters.';
  if($ap!==$ap2)$errors[]='Admin passwords do not match.';
  if(file_exists(__DIR__.'/data/setup.lock'))$errors[]='Setup is locked already.';
  if(!$errors){
    $cfg="<?php\nreturn ".var_export([
      'app_name'=>'Secure Money Transfer','currency_name'=>'Dark-Money','base_url'=>$base,
      'fee_address'=>$fee,'dark_money_address'=>$dark,'btc_usd_rate'=>$rate,
      'admin_user'=>'admin','admin_password_hash'=>password_hash($ap,PASSWORD_DEFAULT),'app_key'=>keygen(),
      'storage'=>__DIR__.'/data/app.sqlite','activation_total_usd'=>11.0,'activation_value_usd'=>10.0,'exchange_fee_usd'=>1.0,
      'payment_mode'=>'btc-manual-review','allow_private_keys'=>false,'created_at'=>gmdate('c')
    ],true).";\n";
    $free="Secure Money Transfer is a Bitcoin-based value management platform for Dark-Money. Dark-Money represents one shared digital value unit whose ownership is divided between activated users. Users create an account, secure it with password and TOTP-based MFA, connect their Bitcoin wallet address, activate the account with a reviewed BTC payment, deposit BTC value, request BTC withdrawals and transfer value internally to other User IDs. The platform uses a dark interface, simple navigation and transparent BTC share calculations. For safety, the website uses manual review for BTC-facing actions and never stores Bitcoin private keys.\n";
    $ht="Options -Indexes\nDirectoryIndex index.php\n<IfModule mod_rewrite.c>\nRewriteEngine On\nRewriteCond %{REQUEST_FILENAME} !-f\nRewriteCond %{REQUEST_FILENAME} !-d\nRewriteRule ^ index.php [L]\n</IfModule>\n<IfModule mod_headers.c>\nHeader always set X-Frame-Options \"DENY\"\nHeader always set X-Content-Type-Options \"nosniff\"\nHeader always set Referrer-Policy \"strict-origin-when-cross-origin\"\nHeader always set Permissions-Policy \"geolocation=(), microphone=(), camera=()\"\nHeader always set Content-Security-Policy \"default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'\"\n</IfModule>\n<FilesMatch \"^(config\\.php|setup\\.php|setup_final_btc\\.php)$\">\nRequire all denied\n</FilesMatch>\n";
    $css=<<<'CSS'
:root{--bg:#060812;--card:#111827;--card2:#151d31;--line:#29364f;--txt:#f7fbff;--mut:#99a8bf;--a:#7c4dff;--b:#00d4ff;--g:#34d399;--r:#ff5c7a}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#1a2440 0,#060812 44%);color:var(--txt);font-family:Inter,system-ui,-apple-system,Segoe UI,Arial,sans-serif}.wrap{max-width:1120px;margin:auto;padding:26px}.nav{display:flex;justify-content:space-between;gap:14px;align-items:center;margin-bottom:24px}.brand{font-weight:900}.brand span{color:var(--b)}a,.btn{color:#fff;text-decoration:none;border:0;border-radius:14px;padding:11px 15px;background:linear-gradient(135deg,var(--a),#4f46e5);font-weight:800;cursor:pointer;display:inline-block}.secondary{background:#121a2b;border:1px solid var(--line)}.links,.tabs{display:flex;gap:9px;flex-wrap:wrap}.card{background:linear-gradient(180deg,rgba(21,29,49,.96),rgba(13,18,30,.96));border:1px solid var(--line);border-radius:24px;padding:24px;margin-bottom:16px;box-shadow:0 20px 70px rgba(0,0,0,.35)}.hero{padding:42px}.hero h1{font-size:42px;line-height:1.05;margin:0 0 14px}.muted{color:var(--mut)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:15px}.field{display:flex;flex-direction:column;gap:7px;margin:12px 0}.field input,.field select{background:#080d18;color:var(--txt);border:1px solid var(--line);border-radius:14px;padding:13px;font-size:15px}.notice{padding:12px 14px;border-radius:14px;border-left:4px solid var(--b);background:#0b1220}.bad{color:var(--r)}.good{color:var(--g)}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid var(--line);padding:11px;text-align:left}code{background:#080d18;border:1px solid var(--line);border-radius:8px;padding:3px 6px;word-break:break-all}.small{font-size:13px}.footer{margin-top:30px;color:var(--mut);font-size:13px}@media(max-width:720px){.wrap{padding:16px}.nav{align-items:flex-start;flex-direction:column}.hero h1{font-size:32px}}
CSS;
    $index=<<<'PHP'
<?php
$config=require __DIR__.'/config.php';
ini_set('session.cookie_httponly','1');ini_set('session.use_strict_mode','1');if(!empty($_SERVER['HTTPS']))ini_set('session.cookie_secure','1');session_name('SMTBTC');session_start();
function db(){static $pdo;global $config;if(!$pdo){if(!is_dir(__DIR__.'/data'))mkdir(__DIR__.'/data',0755,true);$pdo=new PDO('sqlite:'.$config['storage']);$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('PRAGMA foreign_keys=ON');$pdo->exec('CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,user_id TEXT UNIQUE,password_hash TEXT,totp_secret TEXT,wallet_address TEXT,balance_sat INTEGER DEFAULT 0,active INTEGER DEFAULT 0,created_at TEXT)');$pdo->exec('CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY,type TEXT,status TEXT,from_user TEXT,to_user TEXT,amount_sat INTEGER DEFAULT 0,fee_sat INTEGER DEFAULT 0,txid TEXT,details TEXT,created_at TEXT)');$pdo->exec('CREATE TABLE IF NOT EXISTS attempts(id INTEGER PRIMARY KEY,ip TEXT,created_at INTEGER)');}return $pdo;}
function e($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}function now(){return gmdate('c');}function post($k,$d=''){return trim((string)($_POST[$k]??$d));}function csrf(){if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));return $_SESSION['csrf'];}function checkcsrf(){if($_SERVER['REQUEST_METHOD']==='POST'&&!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(400);exit('Invalid CSRF token.');}}function token(){echo '<input type="hidden" name="csrf" value="'.e(csrf()).'">';}
function sat_to_btc($s){return number_format(((int)$s)/100000000,8,'.','');}function btc_to_sat($b){return (int)round(((float)$b)*100000000);}function usd_to_sat($usd){global $config;return (int)round(((float)$usd/$config['btc_usd_rate'])*100000000);}function sat_to_usd($sat){global $config;return (((int)$sat)/100000000)*$config['btc_usd_rate'];}function usd($n){return number_format((float)$n,2,'.',',');}
function btcaddr($v){return preg_match('/^(bc1|tb1|bcrt1|[13mn2])[a-zA-HJ-NP-Z0-9]{25,90}$/',$v);}function txidok($v){return $v===''||preg_match('/^[a-fA-F0-9]{64}$/',$v);}function uid(){return 'DM-'.strtoupper(bin2hex(random_bytes(4)));}function current_user(){if(empty($_SESSION['uid']))return null;$s=db()->prepare('SELECT * FROM users WHERE user_id=?');$s->execute([$_SESSION['uid']]);return $s->fetch(PDO::FETCH_ASSOC)?:null;}function need_user(){if(!current_user()){header('Location:?p=login');exit;}}function need_admin(){if(empty($_SESSION['admin'])){header('Location:?p=admin');exit;}}
function total_sat(){return (int)db()->query('SELECT COALESCE(SUM(balance_sat),0) FROM users WHERE active=1')->fetchColumn();}function share($sat){$t=total_sat();return $t>0?($sat/$t*100):0;}function tx($type,$status,$from,$to,$amt,$fee,$txid,$details){$s=db()->prepare('INSERT INTO transactions(type,status,from_user,to_user,amount_sat,fee_sat,txid,details,created_at) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([$type,$status,$from,$to,$amt,$fee,$txid,$details,now()]);}
function b32e($d){$a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';$o='';for($i=0;$i<strlen($d);$i++)$bits.=str_pad(decbin(ord($d[$i])),8,'0',STR_PAD_LEFT);foreach(str_split($bits,5) as $c){if(strlen($c)<5)$c=str_pad($c,5,'0');$o.=$a[bindec($c)];}return $o;}function b32d($b){$a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$b=strtoupper(preg_replace('/[^A-Z2-7]/','',$b));$bits='';$o='';for($i=0;$i<strlen($b);$i++){ $v=strpos($a,$b[$i]); if($v!==false)$bits.=str_pad(decbin($v),5,'0',STR_PAD_LEFT);}foreach(str_split($bits,8) as $c)if(strlen($c)===8)$o.=chr(bindec($c));return $o;}function secret(){return b32e(random_bytes(20));}function code($sec,$time=null){$time=$time??time();$ctr=floor($time/30);$hash=hash_hmac('sha1',pack('N*',0).pack('N*',$ctr),b32d($sec),true);$off=ord(substr($hash,-1))&15;$v=((ord($hash[$off])&127)<<24)|(ord($hash[$off+1])<<16)|(ord($hash[$off+2])<<8)|ord($hash[$off+3]);return str_pad($v%1000000,6,'0',STR_PAD_LEFT);}function okcode($sec,$c){$c=preg_replace('/\D/','',$c);for($i=-1;$i<=1;$i++)if(hash_equals(code($sec,time()+$i*30),$c))return true;return false;}
function canlogin(){ $ip=$_SERVER['REMOTE_ADDR']??'x';db()->prepare('DELETE FROM attempts WHERE created_at<?')->execute([time()-900]);$s=db()->prepare('SELECT COUNT(*) FROM attempts WHERE ip=?');$s->execute([$ip]);return (int)$s->fetchColumn()<8;}function fail(){db()->prepare('INSERT INTO attempts(ip,created_at) VALUES(?,?)')->execute([$_SERVER['REMOTE_ADDR']??'x',time()]);}
checkcsrf();$p=$_GET['p']??'home';$msg='';$err='';if($p==='logout'){session_destroy();header('Location:?p=home');exit;}if($p==='admin_logout'){unset($_SESSION['admin']);header('Location:?p=home');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if($p==='register'){if(strlen(post('password'))<10)$err='Password must contain at least 10 characters.';elseif(!btcaddr(post('wallet')))$err='Enter a valid Bitcoin wallet address.';else{$u=uid();$sec=secret();db()->prepare('INSERT INTO users(user_id,password_hash,totp_secret,wallet_address,created_at) VALUES(?,?,?,?,?)')->execute([$u,password_hash(post('password'),PASSWORD_DEFAULT),$sec,post('wallet'),now()]);header('Location:?p=mfa&uid='.urlencode($u));exit;}}
 if($p==='login'){if(!canlogin())$err='Too many login attempts.';else{$s=db()->prepare('SELECT * FROM users WHERE user_id=?');$s->execute([post('user_id')]);$u=$s->fetch(PDO::FETCH_ASSOC);if($u&&password_verify(post('password'),$u['password_hash'])&&okcode($u['totp_secret'],post('totp'))){$_SESSION['uid']=$u['user_id'];header('Location:?p=dashboard');exit;}fail();$err='Login failed.';}}
 if($p==='admin'){global $config;if(post('admin_user')===$config['admin_user']&&password_verify(post('password'),$config['admin_password_hash'])){$_SESSION['admin']=1;header('Location:?p=admin_dashboard');exit;}$err='Admin login failed.';}
 if($p==='activation_request'){need_user();$u=current_user();$net=usd_to_sat($config['activation_value_usd']);$fee=usd_to_sat($config['exchange_fee_usd']);$id=post('txid');if(!txidok($id))$err='Enter a valid 64-character BTC transaction ID or leave it empty.';else{tx('activation','pending',$u['user_id'],null,$net,$fee,$id,'Activation review. Expected total BTC: '.sat_to_btc($net+$fee));$msg='Activation request submitted.';}}
 if($p==='deposit'){need_user();$u=current_user();$sat=btc_to_sat(post('btc'));$fee=usd_to_sat($config['exchange_fee_usd']);$id=post('txid');if($sat<=$fee)$err='Deposit must be greater than the 1 USD BTC fee.';elseif(!txidok($id))$err='Enter a valid 64-character BTC transaction ID or leave it empty.';else{tx('deposit','pending',$u['user_id'],null,$sat-$fee,$fee,$id,'BTC deposit review. Gross BTC: '.sat_to_btc($sat));$msg='Deposit request submitted.';}}
 if($p==='withdraw'){need_user();$u=current_user();$gross=btc_to_sat(post('btc'));$fee=usd_to_sat($config['exchange_fee_usd']);if($gross<=$fee||$gross>$u['balance_sat'])$err='Invalid amount. It must include the fee and not exceed your balance.';else{tx('withdrawal','pending',$u['user_id'],null,$gross-$fee,$fee,'','Payout wallet: '.$u['wallet_address']);$msg='Withdrawal request submitted.';}}
 if($p==='transfer'){need_user();$u=current_user();$sat=btc_to_sat(post('btc'));$to=post('to_user');$s=db()->prepare('SELECT * FROM users WHERE user_id=? AND active=1');$s->execute([$to]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)$err='Target User ID not found or inactive.';elseif($to===$u['user_id'])$err='You cannot transfer to yourself.';elseif($sat<=0||$sat>$u['balance_sat'])$err='Invalid transfer amount.';else{$d=db();$d->beginTransaction();$d->prepare('UPDATE users SET balance_sat=balance_sat-? WHERE user_id=?')->execute([$sat,$u['user_id']]);$d->prepare('UPDATE users SET balance_sat=balance_sat+? WHERE user_id=?')->execute([$sat,$to]);tx('transfer','completed',$u['user_id'],$to,$sat,0,'','Internal BTC-value transfer.');$d->commit();$msg='Transfer completed.';}}
 if($p==='settings'){need_user();if(!btcaddr(post('wallet')))$err='Enter a valid Bitcoin wallet address.';else{db()->prepare('UPDATE users SET wallet_address=? WHERE user_id=?')->execute([post('wallet'),current_user()['user_id']]);$msg='Wallet updated.';}}
 if($p==='admin_action'){need_admin();$id=(int)post('txid');$act=post('action');$s=db()->prepare('SELECT * FROM transactions WHERE id=?');$s->execute([$id]);$t=$s->fetch(PDO::FETCH_ASSOC);if($t&&$t['status']==='pending'){$d=db();$d->beginTransaction();if($act==='approve'){if($t['type']==='activation')$d->prepare('UPDATE users SET active=1,balance_sat=balance_sat+? WHERE user_id=?')->execute([$t['amount_sat'],$t['from_user']]);elseif($t['type']==='deposit')$d->prepare('UPDATE users SET balance_sat=balance_sat+? WHERE user_id=?')->execute([$t['amount_sat'],$t['from_user']]);elseif($t['type']==='withdrawal')$d->prepare('UPDATE users SET balance_sat=balance_sat-? WHERE user_id=? AND balance_sat>=?')->execute([$t['amount_sat']+$t['fee_sat'],$t['from_user'],$t['amount_sat']+$t['fee_sat']]);$d->prepare('UPDATE transactions SET status="approved" WHERE id=?')->execute([$id]);}else{$d->prepare('UPDATE transactions SET status="rejected" WHERE id=?')->execute([$id]);}$d->commit();}header('Location:?p=admin_dashboard');exit;}
}
function headx($title){global $config;echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="'.e(@file_get_contents(__DIR__.'/free.txt')).'"><title>'.e($title).' | '.e($config['app_name']).'</title><link rel="stylesheet" href="assets/style.css"></head><body><div class="wrap"><div class="nav"><div class="brand">Secure <span>Money</span> Transfer</div><div class="links"><a class="secondary" href="?p=home">Home</a>';if(current_user())echo '<a class="secondary" href="?p=dashboard">Dashboard</a><a class="secondary" href="?p=logout">Logout</a>';else echo '<a class="secondary" href="?p=register">Register</a><a class="secondary" href="?p=login">Login</a><a class="secondary" href="?p=admin">Admin</a>';echo '</div></div>';}
function footx(){echo '<div class="footer">Bitcoin-facing actions use manual review. No Bitcoin private keys are stored on this website.</div></div></body></html>';}function flash($m,$e){if($m)echo '<div class="notice good">'.e($m).'</div>';if($e)echo '<div class="notice bad">'.e($e).'</div>';}
headx(ucfirst(str_replace('_',' ',$p)));flash($msg,$err);
if($p==='home'){echo '<div class="card hero"><h1>Bitcoin-based Dark-Money share management.</h1><p class="muted">'.e(file_get_contents(__DIR__.'/free.txt')).'</p><p><a class="btn" href="?p=register">Create account</a></p></div><div class="grid"><div class="card"><h3>BTC ledger</h3><p class="muted">Balances and shares are calculated in satoshis.</p></div><div class="card"><h3>TOTP MFA</h3><p class="muted">Every account requires authenticator MFA.</p></div><div class="card"><h3>Safe BTC handling</h3><p class="muted">Manual review, no hot-wallet private keys.</p></div></div>';}
elseif($p==='register'){echo '<div class="card"><h2>Create account</h2><form method="post">';token();echo '<div class="field"><label>Password</label><input type="password" name="password" minlength="10" required></div><div class="field"><label>Your Bitcoin wallet address</label><input name="wallet" required></div><button class="btn">Create account</button></form></div>';}
elseif($p==='mfa'){$id=$_GET['uid']??'';$s=db()->prepare('SELECT * FROM users WHERE user_id=?');$s->execute([$id]);$u=$s->fetch(PDO::FETCH_ASSOC);if(!$u)echo '<div class="card bad">Account not found.</div>';else{echo '<div class="card"><h2>Configure MFA</h2><p>Your User ID: <code>'.e($u['user_id']).'</code></p><p>TOTP secret: <code>'.e($u['totp_secret']).'</code></p><p class="muted">Add the secret to your authenticator app, then log in.</p><a class="btn" href="?p=login">Login</a></div>';}}
elseif($p==='login'){echo '<div class="card"><h2>User login</h2><form method="post">';token();echo '<div class="field"><label>User ID</label><input name="user_id" required></div><div class="field"><label>Password</label><input type="password" name="password" required></div><div class="field"><label>TOTP code</label><input name="totp" required></div><button class="btn">Login</button></form></div>';}
elseif($p==='dashboard'){need_user();$u=current_user();global $config;echo '<div class="grid"><div class="card"><h3>User ID</h3><p><code>'.e($u['user_id']).'</code></p></div><div class="card"><h3>Status</h3><p>'.($u['active']?'<span class="good">Active</span>':'<span class="bad">Not active</span>').'</p></div><div class="card"><h3>Balance</h3><p>'.sat_to_btc($u['balance_sat']).' BTC</p><p class="muted">$'.usd(sat_to_usd($u['balance_sat'])).'</p></div><div class="card"><h3>Share</h3><p>'.usd(share($u['balance_sat'])).'%</p></div></div><div class="tabs"><a class="btn" href="?p=activation_request">Activate</a><a class="btn" href="?p=deposit">Deposit</a><a class="btn" href="?p=withdraw">Withdraw</a><a class="btn" href="?p=transfer">Transfer</a><a class="btn secondary" href="?p=history">History</a><a class="btn secondary" href="?p=settings">Settings</a></div><div class="card"><h2>BTC payment guide</h2><p>BTC/USD rate used by this installation: <code>$'.usd($config['btc_usd_rate']).'</code></p><p>Activation total: <code>'.sat_to_btc(usd_to_sat(11)).' BTC</code>. Dark-Money value: <code>'.sat_to_btc(usd_to_sat(10)).' BTC</code>. Fee: <code>'.sat_to_btc(usd_to_sat(1)).' BTC</code>.</p><p>Dark-Money address: <code>'.e($config['dark_money_address']).'</code></p><p>Fee address: <code>'.e($config['fee_address']).'</code></p></div>';}
elseif($p==='activation_request'){need_user();echo '<div class="card"><h2>Activation request</h2><p class="muted">Submit after sending the activation BTC amount. Admin manually reviews the transaction.</p><form method="post">';token();echo '<div class="field"><label>BTC transaction ID, optional</label><input name="txid"></div><button class="btn">Submit activation request</button></form></div>';}
elseif($p==='deposit'){need_user();echo '<div class="card"><h2>Deposit BTC</h2><p class="muted">Enter gross BTC sent. A 1 USD fee in BTC is deducted after approval.</p><form method="post">';token();echo '<div class="field"><label>Gross BTC amount</label><input type="number" step="0.00000001" min="0.00000001" name="btc" required></div><div class="field"><label>BTC transaction ID, optional</label><input name="txid"></div><button class="btn">Submit deposit review</button></form></div>';}
elseif($p==='withdraw'){need_user();$u=current_user();echo '<div class="card"><h2>Withdraw BTC</h2><p>Available: <code>'.sat_to_btc($u['balance_sat']).' BTC</code></p><p class="muted">Entered BTC is deducted from your balance. Payout is entered BTC minus the 1 USD BTC fee after admin approval.</p><form method="post">';token();echo '<div class="field"><label>Gross BTC to deduct</label><input type="number" step="0.00000001" min="0.00000001" name="btc" required></div><button class="btn">Submit withdrawal review</button></form></div>';}
elseif($p==='transfer'){need_user();echo '<div class="card"><h2>Internal BTC-value transfer</h2><form method="post">';token();echo '<div class="field"><label>Target User ID</label><input name="to_user" required></div><div class="field"><label>BTC amount</label><input type="number" step="0.00000001" min="0.00000001" name="btc" required></div><button class="btn">Transfer</button></form></div>';}
elseif($p==='history'){need_user();$u=current_user();$s=db()->prepare('SELECT * FROM transactions WHERE from_user=? OR to_user=? ORDER BY id DESC LIMIT 100');$s->execute([$u['user_id'],$u['user_id']]);echo '<div class="card"><h2>History</h2><table><tr><th>ID</th><th>Type</th><th>Status</th><th>Amount BTC</th><th>Fee BTC</th><th>TXID</th><th>Date</th></tr>';foreach($s as $r)echo '<tr><td>'.e($r['id']).'</td><td>'.e($r['type']).'</td><td>'.e($r['status']).'</td><td>'.sat_to_btc($r['amount_sat']).'</td><td>'.sat_to_btc($r['fee_sat']).'</td><td><code>'.e($r['txid']).'</code></td><td>'.e($r['created_at']).'</td></tr>';echo '</table></div>';}
elseif($p==='settings'){need_user();$u=current_user();echo '<div class="card"><h2>Settings</h2><form method="post">';token();echo '<div class="field"><label>Bitcoin wallet address</label><input name="wallet" value="'.e($u['wallet_address']).'" required></div><button class="btn">Save</button></form></div>';}
elseif($p==='admin'){echo '<div class="card"><h2>Admin login</h2><form method="post">';token();echo '<div class="field"><label>Admin user</label><input name="admin_user" value="admin" required></div><div class="field"><label>Password</label><input type="password" name="password" required></div><button class="btn">Login</button></form></div>';}
elseif($p==='admin_dashboard'){need_admin();$users=db()->query('SELECT * FROM users ORDER BY id DESC')->fetchAll(PDO::FETCH_ASSOC);$txs=db()->query('SELECT * FROM transactions ORDER BY id DESC LIMIT 120')->fetchAll(PDO::FETCH_ASSOC);echo '<div class="tabs"><a class="btn secondary" href="?p=admin_logout">Admin logout</a></div><div class="grid"><div class="card"><h3>Total Dark-Money BTC value</h3><p>'.sat_to_btc(total_sat()).' BTC</p><p class="muted">$'.usd(sat_to_usd(total_sat())).'</p></div><div class="card"><h3>Users</h3><p>'.count($users).'</p></div></div><div class="card"><h2>Users</h2><table><tr><th>User</th><th>Active</th><th>BTC</th><th>Share</th><th>Wallet</th></tr>';foreach($users as $u)echo '<tr><td><code>'.e($u['user_id']).'</code></td><td>'.($u['active']?'yes':'no').'</td><td>'.sat_to_btc($u['balance_sat']).'</td><td>'.usd(share($u['balance_sat'])).'%</td><td><code>'.e($u['wallet_address']).'</code></td></tr>';echo '</table></div><div class="card"><h2>BTC review queue</h2><table><tr><th>ID</th><th>Type</th><th>Status</th><th>User</th><th>Amount BTC</th><th>Fee BTC</th><th>TXID</th><th>Action</th></tr>';foreach($txs as $t){echo '<tr><td>'.e($t['id']).'</td><td>'.e($t['type']).'</td><td>'.e($t['status']).'</td><td>'.e($t['from_user']).'</td><td>'.sat_to_btc($t['amount_sat']).'</td><td>'.sat_to_btc($t['fee_sat']).'</td><td><code>'.e($t['txid']).'</code></td><td>';if($t['status']==='pending'){echo '<form method="post" action="?p=admin_action">';token();echo '<input type="hidden" name="txid" value="'.e($t['id']).'"><button class="btn" name="action" value="approve">Approve</button> <button class="btn secondary" name="action" value="reject">Reject</button></form>';}echo '</td></tr>';}echo '</table></div>';}
else echo '<div class="card"><h2>Page not found</h2></div>';footx();
PHP;
    w(__DIR__.'/config.php',$cfg);w(__DIR__.'/free.txt',$free);w(__DIR__.'/.htaccess',$ht);w(__DIR__.'/data/.htaccess','Require all denied' . PHP_EOL);w(__DIR__.'/assets/style.css',$css);w(__DIR__.'/index.php',$index);w(__DIR__.'/data/setup.lock','Installed '.gmdate('c').PHP_EOL);$done=true;
  }
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Secure Money Transfer Setup</title><style>body{margin:0;background:#070911;color:#f4f7fb;font-family:system-ui,-apple-system,Segoe UI,Arial}.wrap{max-width:880px;margin:auto;padding:32px}.card{background:#111827;border:1px solid #263247;border-radius:22px;padding:24px;box-shadow:0 18px 60px #0008}.field{display:flex;flex-direction:column;gap:7px;margin:14px 0}input{background:#070911;color:#fff;border:1px solid #263247;border-radius:13px;padding:13px}.btn{background:linear-gradient(135deg,#7c4dff,#4f46e5);border:0;color:white;border-radius:13px;padding:12px 16px;font-weight:800}.bad{color:#ff5c7a}.good{color:#34d399}.muted{color:#9ba8bd}code{background:#070911;border:1px solid #263247;padding:3px 6px;border-radius:8px}</style></head><body><div class="wrap"><div class="card"><h1>Secure Money Transfer BTC Setup</h1><?php if($done): ?><p class="good">Installation completed.</p><p>Created BTC-based Dark-Money website files.</p><p class="bad">Delete this setup file now.</p><p><a class="btn" href="index.php">Open website</a></p><?php else: ?><p class="muted">Creates the final BTC-based version with satoshi ledger, TOTP MFA, manual BTC review and no private-key storage.</p><?php if($errors): ?><ul class="bad"><?php foreach($errors as $er): ?><li><?=h($er)?></li><?php endforeach; ?></ul><?php endif; ?><form method="post"><div class="field"><label>Base URL</label><input name="base_url" value="<?=h((!empty($_SERVER['HTTPS'])?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').rtrim(dirname($_SERVER['SCRIPT_NAME']??''),'/'))?>" required></div><div class="field"><label>Fee Bitcoin address</label><input name="fee_address" required></div><div class="field"><label>Dark-Money Bitcoin address</label><input name="dark_address" required></div><div class="field"><label>BTC/USD rate for fee and activation calculation</label><input type="number" step="0.01" min="1" name="btc_usd_rate" required></div><div class="field"><label>Admin password</label><input type="password" minlength="12" name="admin_password" required></div><div class="field"><label>Repeat admin password</label><input type="password" minlength="12" name="admin_password2" required></div><button class="btn">Generate final BTC website</button></form><?php endif; ?></div></div></body></html>
