<?php
$errors=[];$done=false;
function h($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
function post($k,$d=''){return trim((string)($_POST[$k]??$d));}
function btcaddr($v){return (bool)preg_match('/^(bc1|tb1|bcrt1|[13mn2])[a-zA-HJ-NP-Z0-9]{25,90}$/',$v);}
function wr($p,$c){$d=dirname($p);if(!is_dir($d))mkdir($d,0755,true);file_put_contents($p,$c,LOCK_EX);}
function b32e($d){$a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';$o='';for($i=0;$i<strlen($d);$i++)$bits.=str_pad(decbin(ord($d[$i])),8,'0',STR_PAD_LEFT);foreach(str_split($bits,5) as $c){if(strlen($c)<5)$c=str_pad($c,5,'0');$o.=$a[bindec($c)];}return $o;}
function fake_btc(){return 'tb1q'.substr(strtolower(bin2hex(random_bytes(22))),0,38);} 
function installer_files($demo,$fee,$dark){
$cfg="<?php\nreturn ".var_export(['app_name'=>'Secure Money Transfer','currency_name'=>'Dark-Money','mode'=>$demo?'demo':'production-safe','fee_address'=>$fee,'dark_money_address'=>$dark,'storage'=>__DIR__.'/data/app.sqlite','json_transfer_log'=>__DIR__.'/data/btc_transfer_events.json','demo_simulator_log'=>__DIR__.'/data/demo_simulator_events.json','price_cache'=>__DIR__.'/data/btc_price_cache.json','app_key'=>bin2hex(random_bytes(32)),'created_at'=>gmdate('c'),'allow_private_keys'=>false],true).";\n";
$css=<<<'CSS'
:root{--bg:#060812;--card:#111827;--card2:#151d31;--line:#29364f;--txt:#f7fbff;--mut:#9aa8bd;--a:#7c4dff;--b:#00d4ff;--g:#34d399;--r:#ff5c7a}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top left,#1b2440 0,#060812 46%);color:var(--txt);font-family:Inter,system-ui,-apple-system,Segoe UI,Arial,sans-serif}.wrap{max-width:1120px;margin:auto;padding:26px}.nav{display:flex;justify-content:space-between;gap:14px;align-items:center;margin-bottom:24px}.brand{font-weight:900}.brand span{color:var(--b)}a,.btn{color:#fff;text-decoration:none;border:0;border-radius:14px;padding:11px 15px;background:linear-gradient(135deg,var(--a),#4f46e5);font-weight:800;cursor:pointer;display:inline-block}.secondary{background:#121a2b;border:1px solid var(--line)}.links,.tabs{display:flex;gap:9px;flex-wrap:wrap}.card{background:linear-gradient(180deg,rgba(21,29,49,.96),rgba(13,18,30,.96));border:1px solid var(--line);border-radius:24px;padding:24px;margin-bottom:16px;box-shadow:0 20px 70px rgba(0,0,0,.35)}.hero{padding:42px}.hero h1{font-size:42px;line-height:1.05;margin:0 0 14px}.muted{color:var(--mut)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:15px}.field{display:flex;flex-direction:column;gap:7px;margin:12px 0}.field input,.field select{background:#080d18;color:var(--txt);border:1px solid var(--line);border-radius:14px;padding:13px;font-size:15px}.notice{padding:12px 14px;border-radius:14px;border-left:4px solid var(--b);background:#0b1220}.bad{color:var(--r)}.good{color:var(--g)}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid var(--line);padding:11px;text-align:left}code{background:#080d18;border:1px solid var(--line);border-radius:8px;padding:3px 6px;word-break:break-all}.footer{margin-top:30px;color:var(--mut);font-size:13px}@media(max-width:720px){.wrap{padding:16px}.nav{align-items:flex-start;flex-direction:column}.hero h1{font-size:32px}}
CSS;
$index=<<<'PHP'
<?php
$config=require __DIR__.'/config.php';
ini_set('session.cookie_httponly','1');ini_set('session.use_strict_mode','1');if(!empty($_SERVER['HTTPS']))ini_set('session.cookie_secure','1');session_name('SMTBTC');session_start();
function db(){static $pdo;global $config;if(!$pdo){if(!is_dir(__DIR__.'/data'))mkdir(__DIR__.'/data',0755,true);$pdo=new PDO('sqlite:'.$config['storage']);$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('PRAGMA foreign_keys=ON');$pdo->exec('CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,user_id TEXT UNIQUE,password_hash TEXT,totp_secret TEXT,wallet_address TEXT,balance_sat INTEGER DEFAULT 0,active INTEGER DEFAULT 1,created_at TEXT)');$pdo->exec('CREATE TABLE IF NOT EXISTS txs(id INTEGER PRIMARY KEY,type TEXT,status TEXT,from_user TEXT,to_user TEXT,amount_sat INTEGER,fee_sat INTEGER DEFAULT 0,txid TEXT,details TEXT,created_at TEXT)');}return $pdo;}
function e($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}function now(){return gmdate('c');}function p($k,$d=''){return trim((string)($_POST[$k]??$d));}function csrf(){if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));return $_SESSION['csrf'];}function tok(){echo '<input type="hidden" name="csrf" value="'.e(csrf()).'">';}function chk(){if($_SERVER['REQUEST_METHOD']==='POST'&&!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(400);exit('Invalid CSRF token.');}}
function satbtc($s){return number_format(((int)$s)/100000000,8,'.','');}function btcsat($b){return (int)round(((float)$b)*100000000);}function price_usd(){global $config;$file=$config['price_cache'];$cached=is_file($file)?json_decode(file_get_contents($file),true):null;if($cached&&isset($cached['usd'],$cached['time'])&&time()-$cached['time']<120)return (float)$cached['usd'];$url='https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd&include_last_updated_at=true';$ctx=stream_context_create(['http'=>['timeout'=>4,'header'=>'Accept: application/json\r\n']]);$raw=@file_get_contents($url,false,$ctx);$usd=0;if($raw){$j=json_decode($raw,true);$usd=(float)($j['bitcoin']['usd']??0);}if($usd>0){file_put_contents($file,json_encode(['usd'=>$usd,'time'=>time()],JSON_PRETTY_PRINT),LOCK_EX);return $usd;}if($cached&&isset($cached['usd']))return (float)$cached['usd'];return 0;}function usd_sat($usd){$p=price_usd();return $p>0?(int)round(((float)$usd/$p)*100000000):0;}function satusd($sat){$p=price_usd();return $p>0?(((int)$sat)/100000000)*$p:0;}function usd($n){return number_format((float)$n,2,'.',',');}
function uid(){return 'DM-'.strtoupper(bin2hex(random_bytes(4)));}function btcaddr($v){return preg_match('/^(bc1|tb1|bcrt1|[13mn2])[a-zA-HJ-NP-Z0-9]{25,90}$/',$v);}function txidok($v){return $v===''||preg_match('/^[a-fA-F0-9]{64}$/',$v);}function current_user(){if(empty($_SESSION['uid']))return null;$s=db()->prepare('SELECT * FROM users WHERE user_id=?');$s->execute([$_SESSION['uid']]);return $s->fetch(PDO::FETCH_ASSOC)?:null;}function need_user(){if(!current_user()){header('Location:?p=login');exit;}}
function total_sat(){return (int)db()->query('SELECT COALESCE(SUM(balance_sat),0) FROM users')->fetchColumn();}function share($sat){$t=total_sat();return $t>0?($sat/$t*100):0;}function tx($type,$status,$from,$to,$amt,$fee,$txid,$details){$s=db()->prepare('INSERT INTO txs(type,status,from_user,to_user,amount_sat,fee_sat,txid,details,created_at) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([$type,$status,$from,$to,$amt,$fee,$txid,$details,now()]);}
function log_json($event){global $config;$file=$config['json_transfer_log'];$arr=is_file($file)?json_decode(file_get_contents($file),true):[];if(!is_array($arr))$arr=[];$arr[]=array_merge(['time'=>now()],$event);file_put_contents($file,json_encode($arr,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);}
function b32d($b){$a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$b=strtoupper(preg_replace('/[^A-Z2-7]/','',$b));$bits='';$o='';for($i=0;$i<strlen($b);$i++){ $v=strpos($a,$b[$i]);if($v!==false)$bits.=str_pad(decbin($v),5,'0',STR_PAD_LEFT);}foreach(str_split($bits,8) as $c)if(strlen($c)===8)$o.=chr(bindec($c));return $o;}function code($sec,$time=null){$time=$time??time();$ctr=floor($time/30);$hash=hash_hmac('sha1',pack('N*',0).pack('N*',$ctr),b32d($sec),true);$off=ord(substr($hash,-1))&15;$v=((ord($hash[$off])&127)<<24)|(ord($hash[$off+1])<<16)|(ord($hash[$off+2])<<8)|ord($hash[$off+3]);return str_pad($v%1000000,6,'0',STR_PAD_LEFT);}function okcode($sec,$c){$c=preg_replace('/\D/','',$c);for($i=-1;$i<=1;$i++)if(hash_equals(code($sec,time()+$i*30),$c))return true;return false;}
function b32e($d){$a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';$o='';for($i=0;$i<strlen($d);$i++)$bits.=str_pad(decbin(ord($d[$i])),8,'0',STR_PAD_LEFT);foreach(str_split($bits,5) as $c){if(strlen($c)<5)$c=str_pad($c,5,'0');$o.=$a[bindec($c)];}return $o;}function secret(){return b32e(random_bytes(20));}
chk();$page=$_GET['p']??'home';$msg='';$err='';if($page==='logout'){session_destroy();header('Location:?p=home');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if($page==='register'){if(strlen(p('password'))<10)$err='Password must contain at least 10 characters.';elseif(!btcaddr(p('wallet')))$err='Enter a valid Bitcoin wallet address.';else{$u=uid();$sec=secret();db()->prepare('INSERT INTO users(user_id,password_hash,totp_secret,wallet_address,created_at) VALUES(?,?,?,?,?)')->execute([$u,password_hash(p('password'),PASSWORD_DEFAULT),$sec,p('wallet'),now()]);header('Location:?p=mfa&uid='.urlencode($u));exit;}}
 if($page==='login'){$s=db()->prepare('SELECT * FROM users WHERE user_id=?');$s->execute([p('user_id')]);$u=$s->fetch(PDO::FETCH_ASSOC);if($u&&password_verify(p('password'),$u['password_hash'])&&okcode($u['totp_secret'],p('totp'))){$_SESSION['uid']=$u['user_id'];header('Location:?p=dashboard');exit;}$err='Login failed.';}
 if($page==='deposit'){need_user();$u=current_user();$gross=btcsat(p('btc'));$fee=usd_sat(1);if($fee<=0)$err='Live BTC/USD price is unavailable. Try again later.';elseif($gross<=$fee)$err='Deposit must be greater than the live 1 USD BTC fee.';elseif(!txidok(p('txid')))$err='Invalid transaction ID.';else{$net=$gross-$fee;tx('deposit',$config['mode']==='demo'?'simulated':'recorded',$u['user_id'],null,$net,$fee,p('txid'),'BTC deposit event.');db()->prepare('UPDATE users SET balance_sat=balance_sat+? WHERE user_id=?')->execute([$net,$u['user_id']]);log_json(['type'=>'deposit','user'=>$u['user_id'],'gross_sat'=>$gross,'fee_sat'=>$fee,'net_sat'=>$net,'txid'=>p('txid'),'mode'=>$config['mode']]);$msg='Deposit recorded and Dark-Money share recalculated.';}}
 if($page==='withdraw'){need_user();$u=current_user();$gross=btcsat(p('btc'));$fee=usd_sat(1);if($fee<=0)$err='Live BTC/USD price is unavailable. Try again later.';elseif($gross<=$fee||$gross>$u['balance_sat'])$err='Invalid amount. It must include the live 1 USD BTC fee and not exceed your balance.';else{$net=$gross-$fee;db()->prepare('UPDATE users SET balance_sat=balance_sat-? WHERE user_id=?')->execute([$gross,$u['user_id']]);tx('withdrawal',$config['mode']==='demo'?'simulated':'payout-instruction',$u['user_id'],null,$net,$fee,'','Send to wallet: '.$u['wallet_address']);log_json(['type'=>'withdrawal_instruction','user'=>$u['user_id'],'wallet'=>$u['wallet_address'],'deduct_sat'=>$gross,'fee_sat'=>$fee,'payout_sat'=>$net,'mode'=>$config['mode']]);$msg='Withdrawal instruction recorded. This website does not hold private keys or broadcast payouts.';}}
 if($page==='transfer'){need_user();$u=current_user();$sat=btcsat(p('btc'));$to=p('to_user');$s=db()->prepare('SELECT * FROM users WHERE user_id=?');$s->execute([$to]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)$err='Target User ID not found.';elseif($to===$u['user_id'])$err='You cannot transfer to yourself.';elseif($sat<=0||$sat>$u['balance_sat'])$err='Invalid amount.';else{$d=db();$d->beginTransaction();$d->prepare('UPDATE users SET balance_sat=balance_sat-? WHERE user_id=?')->execute([$sat,$u['user_id']]);$d->prepare('UPDATE users SET balance_sat=balance_sat+? WHERE user_id=?')->execute([$sat,$to]);tx('internal-transfer','completed',$u['user_id'],$to,$sat,0,'','No fee internal transfer.');$d->commit();log_json(['type'=>'internal_transfer','from'=>$u['user_id'],'to'=>$to,'amount_sat'=>$sat]);$msg='Transfer completed.';}}
 if($page==='settings'){need_user();if(!btcaddr(p('wallet')))$err='Enter a valid Bitcoin wallet address.';else{db()->prepare('UPDATE users SET wallet_address=? WHERE user_id=?')->execute([p('wallet'),current_user()['user_id']]);$msg='Wallet updated.';}}
}
function headx($t){global $config;echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="'.e(@file_get_contents(__DIR__.'/free.txt')).'"><title>'.e($t).' | '.e($config['app_name']).'</title><link rel="stylesheet" href="assets/style.css"></head><body><div class="wrap"><div class="nav"><div class="brand">Secure <span>Money</span> Transfer</div><div class="links"><a class="secondary" href="?p=home">Home</a>';if(current_user())echo '<a class="secondary" href="?p=dashboard">Dashboard</a><a class="secondary" href="?p=logout">Logout</a>';else echo '<a class="secondary" href="?p=register">Register</a><a class="secondary" href="?p=login">Login</a>';if($config['mode']==='demo')echo '<a class="secondary" href="demo_transfer_interface.php">Demo simulator</a>';echo '</div></div>';}
function footx(){global $config;echo '<div class="footer">Mode: '.e($config['mode']).'. Live BTC/USD fee conversion uses a cached public price API. No private keys are stored.</div></div></body></html>';}function flash($m,$e){if($m)echo '<div class="notice good">'.e($m).'</div>';if($e)echo '<div class="notice bad">'.e($e).'</div>';}
headx(ucfirst(str_replace('_',' ',$page)));flash($msg,$err);
if($page==='home'){echo '<div class="card hero"><h1>Dark-Money shares based on Bitcoin value.</h1><p class="muted">'.e(file_get_contents(__DIR__.'/free.txt')).'</p><p><a class="btn" href="?p=register">Create account</a></p></div><div class="grid"><div class="card"><h3>Live 1 USD fee</h3><p class="muted">The 1 USD fee is converted to BTC using live cached BTC/USD values.</p></div><div class="card"><h3>One Dark-Money unit</h3><p class="muted">Every balance is a share of one total Dark-Money unit.</p></div><div class="card"><h3>No admin account</h3><p class="muted">The interface is user-based, with JSON event logging for BTC-facing actions.</p></div></div>';}
elseif($page==='register'){echo '<div class="card"><h2>Create account</h2><form method="post">';tok();echo '<div class="field"><label>Password</label><input type="password" name="password" minlength="10" required></div><div class="field"><label>Your Bitcoin wallet address</label><input name="wallet" required></div><button class="btn">Create account</button></form></div>';}
elseif($page==='mfa'){$id=$_GET['uid']??'';$s=db()->prepare('SELECT * FROM users WHERE user_id=?');$s->execute([$id]);$u=$s->fetch(PDO::FETCH_ASSOC);echo $u?'<div class="card"><h2>Configure MFA</h2><p>User ID: <code>'.e($u['user_id']).'</code></p><p>TOTP secret: <code>'.e($u['totp_secret']).'</code></p><a class="btn" href="?p=login">Login</a></div>':'<div class="card bad">Account not found.</div>';}
elseif($page==='login'){echo '<div class="card"><h2>Login</h2><form method="post">';tok();echo '<div class="field"><label>User ID</label><input name="user_id" required></div><div class="field"><label>Password</label><input type="password" name="password" required></div><div class="field"><label>TOTP code</label><input name="totp" required></div><button class="btn">Login</button></form></div>';}
elseif($page==='dashboard'){need_user();$u=current_user();$fee=usd_sat(1);echo '<div class="grid"><div class="card"><h3>User ID</h3><p><code>'.e($u['user_id']).'</code></p></div><div class="card"><h3>Balance</h3><p>'.satbtc($u['balance_sat']).' BTC</p><p class="muted">$'.usd(satusd($u['balance_sat'])).'</p></div><div class="card"><h3>Share</h3><p>'.usd(share($u['balance_sat'])).'%</p></div><div class="card"><h3>Live fee</h3><p>'.satbtc($fee).' BTC</p><p class="muted">1 USD</p></div></div><div class="tabs"><a class="btn" href="?p=deposit">Deposit</a><a class="btn" href="?p=withdraw">Withdraw</a><a class="btn" href="?p=transfer">Transfer</a><a class="btn secondary" href="?p=history">History</a><a class="btn secondary" href="?p=settings">Settings</a></div><div class="card"><h2>BTC addresses</h2><p>Dark-Money address: <code>'.e($GLOBALS['config']['dark_money_address']).'</code></p><p>Fee address: <code>'.e($GLOBALS['config']['fee_address']).'</code></p></div>';}
elseif($page==='deposit'){need_user();echo '<div class="card"><h2>Deposit BTC</h2><p class="muted">Send BTC to the Dark-Money address and submit the gross BTC amount. The live 1 USD BTC fee is deducted.</p><form method="post">';tok();echo '<div class="field"><label>Gross BTC amount</label><input type="number" step="0.00000001" name="btc" required></div><div class="field"><label>BTC TXID, optional in demo</label><input name="txid"></div><button class="btn">Record deposit</button></form></div>';}
elseif($page==='withdraw'){need_user();echo '<div class="card"><h2>Withdraw BTC</h2><p class="muted">A payout instruction is logged. This site does not store private keys or broadcast transactions.</p><form method="post">';tok();echo '<div class="field"><label>Gross BTC to deduct</label><input type="number" step="0.00000001" name="btc" required></div><button class="btn">Create withdrawal instruction</button></form></div>';}
elseif($page==='transfer'){need_user();echo '<div class="card"><h2>Transfer to User ID</h2><form method="post">';tok();echo '<div class="field"><label>Target User ID</label><input name="to_user" required></div><div class="field"><label>BTC amount</label><input type="number" step="0.00000001" name="btc" required></div><button class="btn">Transfer</button></form></div>';}
elseif($page==='history'){need_user();$u=current_user();$s=db()->prepare('SELECT * FROM txs WHERE from_user=? OR to_user=? ORDER BY id DESC LIMIT 100');$s->execute([$u['user_id'],$u['user_id']]);echo '<div class="card"><h2>History</h2><table><tr><th>ID</th><th>Type</th><th>Status</th><th>BTC</th><th>Fee</th><th>TXID</th><th>Date</th></tr>';foreach($s as $r)echo '<tr><td>'.e($r['id']).'</td><td>'.e($r['type']).'</td><td>'.e($r['status']).'</td><td>'.satbtc($r['amount_sat']).'</td><td>'.satbtc($r['fee_sat']).'</td><td><code>'.e($r['txid']).'</code></td><td>'.e($r['created_at']).'</td></tr>';echo '</table></div>';}
elseif($page==='settings'){need_user();$u=current_user();echo '<div class="card"><h2>Settings</h2><form method="post">';tok();echo '<div class="field"><label>Bitcoin wallet address</label><input name="wallet" value="'.e($u['wallet_address']).'" required></div><button class="btn">Save</button></form></div>';}
else echo '<div class="card">Page not found.</div>';footx();
PHP;
$demo=<<<'PHP'
<?php
$config=require __DIR__.'/config.php';
if(($config['mode']??'')!=='demo'){http_response_code(404);exit('Demo interface is disabled.');}
function h($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}function p($k,$d=''){return trim((string)($_POST[$k]??$d));}
function db(){static $pdo;global $config;if(!$pdo){$pdo=new PDO('sqlite:'.$config['storage']);$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);}return $pdo;}function btcsat($b){return (int)round(((float)$b)*100000000);}function satbtc($s){return number_format(((int)$s)/100000000,8,'.','');}
$msg='';$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $uid=p('user_id');$btc=p('btc');$sat=btcsat($btc);$type=p('type','incoming');$s=db()->prepare('SELECT * FROM users WHERE user_id=?');$s->execute([$uid]);$u=$s->fetch(PDO::FETCH_ASSOC);
  if(!$u)$err='User ID not found.';elseif($sat<=0)$err='Enter a positive BTC amount.';else{if($type==='incoming'){db()->prepare('UPDATE users SET balance_sat=balance_sat+? WHERE user_id=?')->execute([$sat,$uid]);}else{db()->prepare('UPDATE users SET balance_sat=MAX(balance_sat-?,0) WHERE user_id=?')->execute([$sat,$uid]);}$event=['time'=>gmdate('c'),'interface'=>'demo_transfer_interface.php','type'=>$type,'user_id'=>$uid,'sat'=>$sat,'btc'=>satbtc($sat)];$file=$config['demo_simulator_log'];$arr=is_file($file)?json_decode(file_get_contents($file),true):[];if(!is_array($arr))$arr=[];$arr[]=$event;file_put_contents($file,json_encode($arr,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);$msg='Demo event saved and account balance updated.';}}
$users=db()->query('SELECT user_id,wallet_address,balance_sat FROM users ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Demo BTC simulator</title><link rel="stylesheet" href="assets/style.css"></head><body><div class="wrap"><div class="nav"><div class="brand">Demo <span>BTC</span> Simulator</div><div class="links"><a class="secondary" href="index.php">Website</a></div></div><?php if($msg):?><div class="notice good"><?=h($msg)?></div><?php endif;?><?php if($err):?><div class="notice bad"><?=h($err)?></div><?php endif;?><div class="card"><h1>Simulate BTC events</h1><p class="muted">This demo-only interface writes events into <code>data/demo_simulator_events.json</code> and updates demo balances. It does not perform real Bitcoin transfers.</p><form method="post"><div class="field"><label>User ID</label><select name="user_id"><?php foreach($users as $u):?><option value="<?=h($u['user_id'])?>"><?=h($u['user_id'])?>, <?=satbtc($u['balance_sat'])?> BTC</option><?php endforeach;?></select></div><div class="field"><label>Event type</label><select name="type"><option value="incoming">Incoming BTC</option><option value="outgoing">Outgoing BTC</option></select></div><div class="field"><label>BTC amount</label><input type="number" step="0.00000001" name="btc" required></div><button class="btn">Save demo event</button></form></div><div class="card"><h2>Demo users</h2><table><tr><th>User ID</th><th>Wallet</th><th>Balance</th></tr><?php foreach($users as $u):?><tr><td><code><?=h($u['user_id'])?></code></td><td><code><?=h($u['wallet_address'])?></code></td><td><?=satbtc($u['balance_sat'])?> BTC</td></tr><?php endforeach;?></table></div></div></body></html>
PHP;
$ht="Options -Indexes\nDirectoryIndex index.php\n<IfModule mod_rewrite.c>\nRewriteEngine On\nRewriteCond %{REQUEST_FILENAME} !-f\nRewriteCond %{REQUEST_FILENAME} !-d\nRewriteRule ^ index.php [L]\n</IfModule>\n<IfModule mod_headers.c>\nHeader always set X-Frame-Options \"DENY\"\nHeader always set X-Content-Type-Options \"nosniff\"\nHeader always set Referrer-Policy \"strict-origin-when-cross-origin\"\nHeader always set Permissions-Policy \"geolocation=(), microphone=(), camera=()\"\nHeader always set Content-Security-Policy \"default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'\"\n</IfModule>\n<FilesMatch \"^(config\\.php|setup\\.php)$\">\nRequire all denied\n</FilesMatch>\n";
return [$cfg,$css,$index,$demo,$ht];
}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $mode=post('mode');$demo=$mode==='demo';$fee=$demo?fake_btc():post('fee_address');$dark=$demo?fake_btc():post('dark_address');
  if(file_exists(__DIR__.'/data/setup.lock'))$errors[]='Setup is locked already.';
  if(!$demo){if(!btcaddr($fee))$errors[]='Enter a valid fee Bitcoin address.';if(!btcaddr($dark))$errors[]='Enter a valid Dark-Money Bitcoin address.';}
  if(!$errors){[$cfg,$css,$index,$demoPhp,$ht]=installer_files($demo,$fee,$dark);wr(__DIR__.'/config.php',$cfg);wr(__DIR__.'/assets/style.css',$css);wr(__DIR__.'/index.php',$index);wr(__DIR__.'/.htaccess',$ht);wr(__DIR__.'/data/.htaccess','Require all denied'.PHP_EOL);wr(__DIR__.'/data/btc_transfer_events.json',"[]\n");wr(__DIR__.'/data/demo_simulator_events.json',"[]\n");
    $free="Secure Money Transfer is a Bitcoin-based interface for Dark-Money. Dark-Money is one shared digital value unit, and every user owns a percentage share based on their BTC-denominated balance. The platform uses password login, TOTP-based MFA, live BTC/USD conversion for the fixed 1 USD fee, internal User ID transfers without fee and a dark, simple interface. The website does not store Bitcoin private keys. BTC-facing actions are recorded as transparent events.\n\nMode: ".($demo?'DEMO':'PRODUCTION-SAFE')."\nDark-Money address: $dark\nFee address: $fee\nTransfer event JSON: data/btc_transfer_events.json\n";
    if($demo){wr(__DIR__.'/demo_transfer_interface.php',$demoPhp);$users=[];$pdo=new PDO('sqlite:'.__DIR__.'/data/app.sqlite');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,user_id TEXT UNIQUE,password_hash TEXT,totp_secret TEXT,wallet_address TEXT,balance_sat INTEGER DEFAULT 0,active INTEGER DEFAULT 1,created_at TEXT)');for($i=1;$i<=2;$i++){ $uid='DM-DEMO-'.$i.'-'.strtoupper(substr(bin2hex(random_bytes(2)),0,4));$pass='DemoPass-'.$i.'-'.substr(bin2hex(random_bytes(3)),0,6);$sec=b32e(random_bytes(20));$wallet=fake_btc();$pdo->prepare('INSERT INTO users(user_id,password_hash,totp_secret,wallet_address,balance_sat,active,created_at) VALUES(?,?,?,?,?,?,?)')->execute([$uid,password_hash($pass,PASSWORD_DEFAULT),$sec,$wallet,0,1,gmdate('c')]);$users[]=[$uid,$pass,$sec,$wallet];}
      $free.="\nDemo simulator interface: demo_transfer_interface.php\nDemo simulator JSON: data/demo_simulator_events.json\nDemo mode uses random test-style BTC addresses and does not perform real transfers. Use the simulator interface to create incoming or outgoing demo BTC events for the demo users.\n\nDemo users:\n";foreach($users as $u){$free.="User ID: {$u[0]}\nPassword: {$u[1]}\nMFA TOTP secret: {$u[2]}\nWallet: {$u[3]}\n\n";}}
    wr(__DIR__.'/free.txt',$free);wr(__DIR__.'/data/setup.lock','Installed '.gmdate('c').' mode '.($demo?'demo':'production-safe').PHP_EOL);$done=true;}}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Secure Money Transfer Setup</title><style>body{margin:0;background:#070911;color:#f4f7fb;font-family:system-ui,-apple-system,Segoe UI,Arial}.wrap{max-width:920px;margin:auto;padding:32px}.card{background:#111827;border:1px solid #263247;border-radius:22px;padding:24px;box-shadow:0 18px 60px #0008}.field{display:flex;flex-direction:column;gap:7px;margin:14px 0}input{background:#070911;color:#fff;border:1px solid #263247;border-radius:13px;padding:13px}.btn{background:linear-gradient(135deg,#7c4dff,#4f46e5);border:0;color:white;border-radius:13px;padding:12px 16px;font-weight:800;margin-right:8px}.secondary{background:#121a2b;border:1px solid #263247}.bad{color:#ff5c7a}.good{color:#34d399}.muted{color:#9ba8bd}code{background:#070911;border:1px solid #263247;padding:3px 6px;border-radius:8px}</style></head><body><div class="wrap"><div class="card"><h1>Secure Money Transfer Setup</h1><?php if($done):?><p class="good">Setup completed.</p><p>Created the no-admin BTC-based website. Delete <code>setup.php</code> now.</p><p><a class="btn" href="index.php">Open website</a><?php if(isset($demo)&&$demo):?><a class="btn secondary" href="demo_transfer_interface.php">Open demo simulator</a><?php endif;?></p><?php else:?><p class="muted">No admin accounts. The 1 USD fee is converted live to BTC. Production-safe mode records BTC events without storing private keys. Demo mode creates two demo users, random test-style BTC addresses and a simulator interface.</p><?php if($errors):?><ul class="bad"><?php foreach($errors as $er):?><li><?=h($er)?></li><?php endforeach;?></ul><?php endif;?><form method="post"><div class="field"><label>Fee Bitcoin address, production-safe mode only</label><input name="fee_address"></div><div class="field"><label>Dark-Money Bitcoin address, production-safe mode only</label><input name="dark_address"></div><button class="btn" name="mode" value="production">Install production-safe BTC mode</button><button class="btn secondary" name="mode" value="demo">Install demo mode with two users</button></form><?php endif;?></div></div></body></html>
